mysite/main/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name = 'homepage'),
    path('register/', views.register, name = 'register'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('tinymce.urls'))
]

mysite/main/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Tutorial(models.Model):
	tutorial_title = models.CharField(max_length = 200)
	tutorial_published = models.DateTimeField("date published", default = datetime.now())
	tutorial_content = models.TextField()

	def __str__(self):
		return self.tutorial_title

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	email_confirmed = models.BooleanField(default=False)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)
	instance.profile.save()

mysite/mysite/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
	#first_name = forms.CharField(max_length = 30, required = False, help_text = 'Optional.')
	#last_name = forms.CharField(max_length = 30, required = False, help_text = 'Optional.')
	email = forms.CharField(max_length = 254, required = True, help_text = 'Required. Provide a valid email address.')

	class Meta:
		model = User
		fields = ('username', 'email', 'password1', 'password2')

mysite/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Tutorial
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import logout, authenticate, login
from mysite.forms import RegistrationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from mysite.tokens import account_activation_token

# Create your views here.

def homepage(request):
	return render(request = request,
				  template_name = 'main/home.html',
				  context = {"tutorials": Tutorial.objects.all()})

def register(request):
	if request.method == "POST":
		form = RegistrationForm(request.POST)
		if form.is_valid():
			user = form.save(commit=False)
			user.is_active = False
			user.save()
			current_site = get_current_site(request)
			subject = 'Activate Your MySite Account'
			message = render_to_string('main/account_activation_email.html', {
				'user': user,
				'domain': current_site.domain,
				'uid': urlsafe_base64_encode(force_bytes(user.pk)),
				'token': account_activation_token.make_token(user),
			})
			user.email_user(subject, message)
			return redirect('main:account_activation_sent')
	else:
		form = RegistrationForm()
	return render(request = request,
				  template_name = "main/register.html",
				  context={"form":form})

def account_activation_sent(request):
	return render(request, 'main/account_activation_sent.html')

def activate(request, uidb64, token):
	try:
		uid = force_text(urlsafe_base64_decode(uidb64))
		user = User.objects.get(pk=uid)
	except (TypeError, ValueError, OverflowError, User.DoesNotExist):
		user = None

	if user is not None and account_activation_token.check_token(user, token):
		user.is_active = True
		user.profile.email_confirmed = True
		user.save()
		login(request, user)
		return redirect('main:homepage')
	else:
		return render(request, 'main/account_activation_invalid.html')

mysite/main/templates/main/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'main:activate' uidb64=uid token=token %}
{% endautoescape %}

mysite/main/templates/main/account_activation_invalid.html
{% extends 'main/header.html' %}

{% block content %}
  <p>The confirmation link was invalid, possibly because it has already been used.</p>
{% endblock %}

mysite/main/templates/main/account_activation_sent.html
{% extends 'main/header.html' %}

{% block content %}
  <p>Please confirm your email address to complete the registration. </p>
{% endblock %}

mysite/main/templates/main/header.html
<head>
	{% load static %}
	<link href = "{% static 'tinymce/css/prism.css' %}", rel = 'stylesheet'>
	<!-- Compiled and minified CSS -->
    <link href = "{% static 'main/css/materialize.css' %}", rel = 'stylesheet'>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
	<div class="navbar-fixed">
	    <nav>
	      <div class="nav-wrapper">
	        <a href="#!" class="brand-logo">Tech Turtles</a>
	        <ul class="right hide-on-med-and-down">
	        	<li><a href="/admin">Admin</a></li>
	        	<li><a href="/">Home</a></li>
	        	<li><a href="/blog">Blog</a></li>
	          	<li><a href="/register">Register</a></li>
	          	<li><a href="/login">Login</a></li>
	        </ul>
	      </div>
	    </nav>
  	</div>
  	<div class = "container">
  		<br>
		{% block content %}
		{% endblock %}
		<br><br>
	</div>

	<script src = "{% static 'tinymce/js/prism.js' %}"></script>
	<footer class="page-footer">
		<div class="container">
			<div class="row">
			  <div class="col l6 s12">
			    <h5 class="white-text">You've reached the end!</h5>
			    <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
			  </div>
			  <div class="col l4 offset-l2 s12">
			    <h5 class="white-text">Links</h5>
			    <ul>
			      <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
			      <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
			      <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
			      <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
			    </ul>
			  </div>
			</div>
			</div>
			<div class="footer-copyright">
			<div class="container">
			© 2020 Tech_turtles.com
			<a class="grey-text text-lighten-4 right" href="#!">More Links</a>
			</div>
		</div>
    </footer>
</body>

mysite/main/templates/main/home.html
{% extends 'main/header.html' %}

{% block content %}
<div class="row">
	{% for tut in tutorials %}
	    <div class="col s12 m6 l12">
	      <div class="card blue-grey darken-1">
	        <div class="card-content white-text">
	          <span class="card-title">{{tut.tutorial_title}}</span>
	          <p>{{tut.tutorial_published}}</p>
	          <p>{{tut.tutorial_content|safe}}</p>
	        </div>
	        <div class="card-action">
	          <a href="#">View</a>
	        </div>
	      </div>
	    </div>
    {% endfor %}
</div>
{% endblock %}

mysite/main/templates/main/register.html
{% extends 'main/header.html' %}

{% block content %}
	<form method = "POST">
		{% csrf_token %}
		{{form.as_p}}

		<button class="btn btn-outline-info" type = "submit">Register</button>
	</form>

	If you already have an account, <a href = '/login' target = 'self'><strong>login</strong></a> instead.
{% endblock %}